version: '3'
services:
  mongo:
    image: mongodb/mongodb-community-server:latest # On which image container will build
    ports:
      - '27017:27017'

  api-server:
    image: server
    ports:
      - '5001:5001'
    depends_on:
      - mongo
    environment:
      MONGO_URI: 'mongodb://mongo:27017'
